# Generated by Django 5.0.1 on 2024-02-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HalfYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1400, 1400), (1401, 1401), (1402, 1402), (1403, 1403), (1404, 1404), (1405, 1405), (1406, 1406), (1407, 1407), (1408, 1408), (1409, 1409), (1410, 1410), (1411, 1411), (1412, 1412), (1413, 1413), (1414, 1414), (1415, 1415), (1416, 1416), (1417, 1417), (1418, 1418), (1419, 1419)], default=1402, verbose_name='سال')),
                ('half', models.IntegerField(choices=[(1, 'اول'), (2, 'دوم')], default=2, verbose_name='نیمسال')),
            ],
            options={
                'verbose_name': 'نیمسال',
                'verbose_name_plural': 'نیمسال ها',
                'unique_together': {('year', 'half')},
            },
        ),
    ]
