# Generated by Django 5.0.1 on 2024-02-02 11:01

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calander', '0002_repetedevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('on_day', django_jalali.db.models.jDateField(default='1402-11-13', help_text='تاریخ را به فرمت سال-ماه-روز وارد کنید. مثال: <br>1402-11-13', verbose_name='روز')),
                ('start_time', models.TimeField(default='14:31', help_text='زمان را به فرمت ساعت:دقیقه وارد کنید. مثال: <br> 12:30', verbose_name='زمان شروع')),
                ('end_time', models.TimeField(default='14:31', help_text='زمان را به فرمت ساعت:دقیقه وارد کنید. مثال: <br> 12:35', verbose_name='زمان پایان')),
            ],
            options={
                'verbose_name': 'رویداد یک بار',
                'verbose_name_plural': 'رویداد های یک بار',
            },
        ),
    ]
